FROM python:3.10-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y libpq-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy and install Python dependencies
COPY ./src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./src/ .

# Expose port and run application
EXPOSE 8000
CMD ["uvicorn", "poke_api:app", "--host", "0.0.0.0", "--port", "8000"]

